### ISSUE TITLE
compile.sh not up-to-date 

### ISSUE THREAD

**Issue by GanbaruTobi** [IntelLabs/kafl.targets#39]
The root dir compile.sh content refers other compile.sh files that don't exist in the repository:
```bash
echo "Build samples for Linux kernel targets..."
echo "-----------------------------------------"
cd linux_x86_64
bash compile.sh
cd ../

echo "Build samples for Linux userspace targets..."
echo "--------------------------------------------"
cd linux_x86_64-userspace
bash compile.sh
cd ../


echo "Build samples MacOS kernel targets..."
echo "-------------------------------------"
cd macOS_x86_64
bash compile.sh
cd ../

echo "Build samples for Windows kernel targets..."
echo "-------------------------------------------"
cd windows_x86_64
bash compile.sh
cd ../
```

If looking for compile.sh files it looks like this:
```bash
(kafl) [gbaru@arch-desktop-fuzz kafl.targets]$ find . -type f -name compile.sh
./compile.sh
./macOS_x86_64/compile.sh
./macOS_x86_64/vuln_driver/compile.sh
```

**Comment by il-steffen** [comment]
I think these files are obsolete, the windows/linux examples are documented here https://intellabs.github.io/kAFL/index.html

cc @Wenzel

**Comment by Wenzel** [comment]
Hi @GanbaruTobi , @il-steffen 

Thanks for opening this issue, the compile.sh scripts are not used anymore.
The examples who are maintained and documented are linux user/kernel and windows user / kernel.

MacOS, UEFI and Zephyr should be considered as either unmaintained or not up to date with the latest changes at this point.
